repo fix

diff --git a/SlackBuilds/slapt-get/slapt-get.SlackBuild b/SlackBuilds/slapt-get/slapt-get.SlackBuild
--- a/SlackBuilds/slapt-get/slapt-get.SlackBuild
+++ b/SlackBuilds/slapt-get/slapt-get.SlackBuild
@@ -1,8 +1,8 @@
-#!/bin/sh
+#!/bin/bash
 
-# Slackware build script for slackrepo
+# Slackware build script for slapt-get
 
-# Copyright 2014 David Spencer, Baildon, West Yorkshire, U.K.
+# Copyright 2023 Vijay Marcel
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,19 +22,52 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-PRGNAM=slackrepo
-VERSION=${VERSION:-0.3}
+cd $(dirname $0) ; CWD=$(pwd)
+
+PRGNAM=slapt-get
+VERSION=${VERSION:-0.11.10}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
+PKGTYPE=${PKGTYPE:-tgz}
 
-ARCH='noarch'
+if [ -z "$ARCH" ]; then
+case "$( uname -m )" in
+    i?86) ARCH=i586 ;;
+    arm*) ARCH=arm ;;
+aarch64*) ARCH=aarch64 ;;
+       *) ARCH=$( uname -m ) ;;
+esac
+fi
 
-CWD=$(pwd)
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
+  exit 0
+fi
+
+
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-march=i586 -mtune=i686 -pipe -O2 -fPIC"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-march=i686 -mtune=i686 -pipe -O2 -fPIC"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-march=x86-64 -mtune=generic -pipe -O2 -fPIC"
+  LIBDIRSUFFIX="64"
+else
+  SLKCFLAGS="-O2"
+  LIBDIRSUFFIX=""
+fi
+
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -49,50 +82,24 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-mkdir -p $PKG/usr/sbin
-cp -a $PRGNAM $PKG/usr/sbin
-# Who needs smudge filters anyway?
-sed -i -e "s/%PKGID%/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}/" $PKG/usr/sbin/$PRGNAM
+CFLAGS="$SLKCFLAGS"   CXXFLAGS="$SLKCFLAGS" meson setup build --prefix=/usr --libdir=/usr/lib${LIBDIRSUFFIX}  --sysconfdir=/etc --mandir=/usr/man --buildtype=release
+meson compile -C build
+DESTDIR="$PKG" meson install -C build
 
-mkdir -p $PKG/usr/bin
-ln -sr $PKG/usr/sbin/$PRGNAM $PKG/usr/bin/
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
-mkdir -p $PKG/usr/libexec
-cp -a libexec/ $PKG/usr/libexec/$PRGNAM
-
-mkdir -p $PKG/usr/share
-cp -a share/ $PKG/usr/share/$PRGNAM
-
-mkdir -p $PKG/var/lib/$PRGNAM
-mkdir -p $PKG/var/log/$PRGNAM
-
-mkdir -p $PKG/etc/$PRGNAM
-for conffile in etc/slackrepo_*.conf; do
-  repo=$(basename $conffile .conf | sed 's/slackrepo_//')
-  cp -a $conffile $PKG/etc/$PRGNAM/$(basename $conffile).new
-  mkdir -p $PKG/etc/$PRGNAM/$repo/hintfiles
-done
-
-install -m 750 -d $PKG/etc/sudoers.d
-install -m 640 etc/sudoers.d/$PRGNAM $PKG/etc/sudoers.d/$PRGNAM.new
-
-mkdir -p $PKG/usr/man
-cp -a man/* $PKG/usr/man/
 find $PKG/usr/man -type f -exec gzip -9 {} \;
+for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a \
-  BUGS LICENCE NEWS README TODO \
-  $PKG/usr/doc/$PRGNAM-$VERSION
+mv -v $PKG/usr/share/doc/* $PKG/usr/doc/$PRGNAM-$VERSION
+rm -rvf $PKG/usr/share/doc 
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
-( cd $PKG
-  find etc -type f -name '*.new' -print0 | xargs --null printf "config '%s'\n"
-) >> $PKG/install/doinst.sh
-
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
