Update llvm.SlackBuild

diff --git a/SlackBuilds/llvm/llvm.SlackBuild b/SlackBuilds/llvm/llvm.SlackBuild
--- a/SlackBuilds/llvm/llvm.SlackBuild
+++ b/SlackBuilds/llvm/llvm.SlackBuild
@@ -3,7 +3,7 @@
 # Slackware build script for llvm
 
 # Copyright 2008-2016 Heinz Wiesinger, Amsterdam, The Netherlands
-# Copyright 2012, 2013, 2014, 2015, 2016, 2018, 2019, 2020, 2021, 2022, 2023, 2024  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2012, 2013, 2014, 2015, 2016, 2018, 2019, 2020, 2021  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -26,14 +26,14 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=llvm
-VERSION=${VERSION:-$(echo llvmorg-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-1}
+VERSION=${VERSION:-$(echo llvm-*.tar.xz | rev | cut -f 4- -d . | cut -f 1 -d - | rev)}
+BUILD=${BUILD:-2}
 
 NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) ARCH=i686 ;;
+    i?86) ARCH=i586 ;;
     arm*) ARCH=arm ;;
        *) ARCH=$( uname -m ) ;;
   esac
@@ -52,16 +52,15 @@ if [ "$BUILD_CLANGD" = "NO" ]; then
   CLANGD="-DCLANG_ENABLE_CLANGD=OFF"
 fi
 
-# Select projects to build:
-if [ "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
-  # bolt and flang are not available on 32-bit
-  LLVM_ENABLE_PROJECTS=${LLVM_ENABLE_PROJECTS:-"clang;clang-tools-extra;compiler-rt;lld;lldb;llvm;mlir;openmp;polly"}
-else
-  LLVM_ENABLE_PROJECTS=${LLVM_ENABLE_PROJECTS:-"bolt;clang;clang-tools-extra;compiler-rt;flang;lld;lldb;llvm;mlir;openmp;polly"}
+# Building lld will be determined automatically unless BUILD_LLD is
+# preset to YES or NO:
+if [ -z $BUILD_LLD ]; then
+  if [ "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
+    BUILD_LLD=NO
+  else
+    BUILD_LLD=YES
+  fi
 fi
-
-# Select runtimes to build:
-LLVM_ENABLE_RUNTIMES=${LLVM_ENABLE_RUNTIMES:-"libcxx;libcxxabi"}
 
 # If the variable PRINT_PACKAGE_NAME is set, then this script will report what
 # the name of the created package would be, and then exit. This information
@@ -73,45 +72,82 @@ fi
 
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-$PKGNAM
-BUILDDIR=${TMP}/llvm-build-${VERSION}
-
-# Ignore that which should be ignored to avoid long build times and
-# massive warning spew:
-IGNORE_GNU_EXTENSIONS=${IGNORE_GNU_EXTENSIONS:--Wno-unknown-warning-option -Wno-gnu-line-marker -Wno-gnu-anonymous-struct -Wno-gnu-include-next}
 
 if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686 $IGNORE_GNU_EXTENSIONS"
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=pentium4 -mtune=generic $IGNORE_GNU_EXTENSIONS"
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC $IGNORE_GNU_EXTENSIONS"
+  SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
 else
-  SLKCFLAGS="-O2 $IGNORE_GNU_EXTENSIONS"
+  SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
 fi
 
+# Python2 short version:
+# PY2=$(python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())' | cut -f 2 -d n | cut -f 1 -d /)
 # Python3 short version:
 PY3=$(python3 -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())' | cut -f 2 -d n | cut -f 1 -d /)
 
-rm -rf $PKG $BUILDDIR
-mkdir -p $TMP $PKG $BUILDDIR
-cd $BUILDDIR
+# Sadly, glibc-2.30 exposed some sort of problem with clang and icecream.
+# The symptom is a compile failure that says none of the types in
+# <linux/types.h> are defined, even though they are. gcc/g++ seem unaffected.
+# For now, not much choice other than to disable this.
+# Don't use icecream:
+#PATH=$(echo $PATH | sed "s|/usr/libexec/icecc/bin||g" | tr -s : | sed "s/^://g" | sed "s/:$//g")
 
-# Add a fake configure script so the cleanup script used here at Slackware
-# knows to delete this stuff later. Other folks can just ignore this... it
-# doesn't have any other purpose.
-touch configure
-chmod 755 configure
+rm -rf $PKG
+mkdir -p $TMP $PKG
+cd $TMP
+rm -rf $PKGNAM-${VERSION}.src $PKGNAM-${VERSION}
+tar xvf $CWD/$PKGNAM-$VERSION.src.tar.xz || exit 1
 
-echo "Extracting $CWD/llvmorg-$VERSION.tar.?z..."
-tar xf $CWD/llvmorg-$VERSION.tar.?z || exit 1
-cd llvm-project-llvmorg-$VERSION || cd llvmorg-$VERSION || exit 1
+cd $PKGNAM-${VERSION}/tools || cd $PKGNAM-${VERSION}.src/tools || exit 1
+  tar xvf $CWD/clang-$VERSION.src.tar.xz || exit 1
+  mv clang-${VERSION} clang 2>/dev/null || mv clang-${VERSION}.src clang || exit 1
+  #tar xvf $CWD/flang-$VERSION.src.tar.xz || exit 1
+  #mv flang-${VERSION} flang 2>/dev/null || mv flang-${VERSION}.src flang || exit 1
+  tar xvf $CWD/lldb-$VERSION.src.tar.xz || exit 1
+  mv lldb-${VERSION} lldb 2>/dev/null || mv lldb-${VERSION}.src lldb || exit 1
+  if [ "$BUILD_LLD" = "YES" ]; then
+    tar xvf $CWD/lld-$VERSION.src.tar.xz || exit 1
+    mv lld-${VERSION} lld 2>/dev/null || mv lld-${VERSION}.src lld || exit 1
+  fi
+cd ../
 
-# Support GCC built for i?86-slackware-linux:
-# zcat $CWD/clang.toolchains.32-bit.triple.diff.gz | patch -p2 --verbose || exit 1
+cd tools/clang/tools || exit 1
+  tar xvf $CWD/clang-tools-extra-$VERSION.src.tar.xz || exit 1
+  mv clang-tools-extra-${VERSION} extra 2>/dev/null \
+    || mv clang-tools-extra-${VERSION}.src extra || exit 1
+  # HACK # Otherwise the build fails because files aren't found.
+  rm -rf $TMP/clang-tools-extra
+  cp -a extra $TMP/clang-tools-extra
+cd ../../../
+
+cd projects || exit 1
+  tar xvf $CWD/compiler-rt-$VERSION.src.tar.xz || exit 1
+  mv compiler-rt-${VERSION} compiler-rt 2>/dev/null || mv compiler-rt-${VERSION}.src compiler-rt || exit 1
+  tar xvf $CWD/openmp-$VERSION.src.tar.xz || exit 1
+  mv openmp-${VERSION} openmp 2>/dev/null || mv openmp-${VERSION}.src openmp || exit 1
+  tar xvf $CWD/libcxx-${VERSION}.src.tar.xz || exit 1
+  mv libcxx-${VERSION} libcxx 2>/dev/null || mv libcxx-${VERSION}.src libcxx || exit 1
+  tar xvf $CWD/libcxxabi-${VERSION}.src.tar.xz || exit 1
+  mv libcxxabi-${VERSION} libcxxabi 2>/dev/null || mv libcxxabi-${VERSION}.src libcxxabi || exit 1
+  tar xvf $CWD/polly-$VERSION.src.tar.xz || exit 1
+  mv polly-${VERSION} polly 2>/dev/null || mv polly-${VERSION}.src polly || exit 1
+  # We just need a header file from this...
+  tar xvf $CWD/libunwind-${VERSION}.src.tar.xz || exit 1
+  mv libunwind-${VERSION} libunwind || mv libunwind-${VERSION}.src libunwind || exit 1
+cd ../
+
+# Support GCC built for i586-slackware-linux:
+zcat $CWD/clang.toolchains.i586.triple.diff.gz | patch -p1 --verbose || exit 1
+
+# Hack to fix build with polly. Maybe we should just not use polly... ?
+zcat $CWD/llvm.polly.hack.diff.gz | patch -p1 --verbose || exit 1
 
 chown -R root:root .
 find . \
@@ -122,9 +158,12 @@ find . \
 
 mkdir build
 cd build
+  mkdir include
+  # Copy this LLVM libunwind header or it won't be found:
+  cp -a ../projects/libunwind/include/mach-o include
+  # Nuke LLVM libunwind as it conflicts with the one already on the system:
+  rm -r ../projects/libunwind
   cmake -GNinja \
-
-
     -DCMAKE_C_COMPILER="clang" \
     -DCMAKE_CXX_COMPILER="clang++" \
     -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
@@ -132,9 +171,7 @@ cd build
     -DCMAKE_INSTALL_PREFIX=/usr \
     -DLLVM_LIBDIR_SUFFIX=${LIBDIRSUFFIX} \
     -DCMAKE_BUILD_TYPE=Release \
-    -DLLVM_BUILD_LLVM_DYLIB=ON \
-    -DLLVM_LINK_LLVM_DYLIB=ON \
-    -DCLANG_LINK_CLANG_DYLIB=ON \
+    -DBUILD_SHARED_LIBS=ON \
     -DLLVM_USE_LINKER=gold \
     -DLLVM_ENABLE_RTTI=ON \
     -DLLVM_ENABLE_FFI=ON \
@@ -145,7 +182,8 @@ cd build
     -DLLVM_TARGETS_TO_BUILD="host;AMDGPU;BPF" \
     -DLLDB_USE_SYSTEM_SIX=1 \
     $CLANGD \
-    ../  || exit 1
+    ..  || exit 1
+
   "${NINJA:=ninja}" $NUMJOBS || exit 1
   DESTDIR=$PKG "$NINJA" install || exit 1
 cd ..
@@ -168,31 +206,31 @@ if [ ! -r $PKG/usr/bin/lit-cpuid ]; then
   chown root:root $PKG/usr/bin/lit-cpuid
   chmod 755 $PKG/usr/bin/lit-cpuid
 fi
-
 # Remove symlink to libgomp, which is already provided by gcc:
 rm -f $PKG/usr/lib$LIBDIRSUFFIX/libgomp.so
 
 # Install Python bindings:
-for pyver in ${PY3}; do
+for pyver in ${PY2} ${PY3}; do
   mkdir -p "$PKG/usr/lib$LIBDIRSUFFIX/python$pyver/site-packages"
-  cp -a clang/bindings/python/clang "$PKG/usr/lib$LIBDIRSUFFIX/python$pyver/site-packages/"
+  cp -a tools/clang/bindings/python/clang "$PKG/usr/lib$LIBDIRSUFFIX/python$pyver/site-packages/"
 done
 
 # Remove bundled python-six:
-rm -f "$PKG/usr/lib$LIBDIRSUFFIX/python2*/site-packages/six.py"
+rm -f "$PKG/usr/lib$LIBDIRSUFFIX/python${PY2}/site-packages/six.py"
 
 # Compile Python scripts:
+# python -m compileall "$PKG/usr/lib$LIBDIRSUFFIX/python${PY2}/site-packages/clang"
+# python -O -m compileall "$PKG/usr/lib$LIBDIRSUFFIX/python${PY2}/site-packages/clang"
 python3 -m compileall "$PKG/usr/lib$LIBDIRSUFFIX/python${PY3}/site-packages/clang"
 python3 -O -m compileall "$PKG/usr/lib$LIBDIRSUFFIX/python${PY3}/site-packages/clang"
+# python -m compileall "$PKG/usr/lib$LIBDIRSUFFIX/python${PY2}/site-packages/lldb"
+# python -O -m compileall "$PKG/usr/lib$LIBDIRSUFFIX/python${PY2}/site-packages/lldb"
 python3 -m compileall "$PKG/usr/share/scan-view"
 python3 -O -m compileall "$PKG/usr/share/scan-view"
 python3 -m compileall "$PKG/usr/share/clang"
 python3 -O -m compileall "$PKG/usr/share/clang"
 python3 -m compileall "$PKG/usr/share/opt-viewer"
 python3 -O -m compileall "$PKG/usr/share/opt-viewer"
-
-# Nevermind, we're not shipping this python2 crap:
-rm -rf $PKG/usr/lib$LIBDIRSUFFIX/python2*
 
 # Move man page directory:
 mv $PKG/usr/share/man $PKG/usr/
@@ -210,17 +248,25 @@ for i in $( find $PKG/usr/man -type l ) ; do
   rm $i
 done
 
-# Just copy anything top or next level that looks like it might be docs.
-# Maybe we'll include it someday. ;-)
-mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION
-cp -a *.{txt,md,TXT,rst} $PKG/usr/doc/$PKGNAM-$VERSION
-cp -a --parents */*.{txt,md,TXT,rst} $PKG/usr/doc/$PKGNAM-$VERSION
-cp -a --parents */README* $PKG/usr/doc/$PKGNAM-$VERSION
-find $PKG/usr/doc/$PKGNAM-$VERSION -name CMakeLists.txt -exec rm -f "{}" \;
-rmdir $PKG/usr/doc/$PKGNAM-$VERSION/* 2> /dev/null
+mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION/{clang,lldb,clang-tools-extra,compiler-rt,openmp,polly}
+cp -a CREDITS* LICENSE* README* $PKG/usr/doc/$PKGNAM-$VERSION
+cp -a tools/clang/{INSTALL,LICENSE,NOTES,README}* \
+  $PKG/usr/doc/$PKGNAM-$VERSION/clang
+cp -a tools/lldb/{CODE_OWNERS,INSTALL,LICENSE}* \
+  $PKG/usr/doc/$PKGNAM-$VERSION/lldb
+cp -a tools/clang/tools/extra/{CODE_OWNERS,LICENSE,README}* \
+  $PKG/usr/doc/$PKGNAM-$VERSION/clang-tools-extra
+cp -a projects/compiler-rt/{CODE_OWNERS,CREDITS,LICENSE,README}* \
+  $PKG/usr/doc/$PKGNAM-$VERSION/compiler-rt
+cp -a projects/openmp/{CREDITS,LICENSE}* \
+  $PKG/usr/doc/$PKGNAM-$VERSION/openmp
+cp -a projects/polly/{CREDITS,LICENSE,README}* \
+  $PKG/usr/doc/$PKGNAM-$VERSION/polly
+mv $PKG/usr/docs/llvm/* $PKG/usr/doc/$PKGNAM-$VERSION
+rm -rf $PKG/usr/docs
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n --remove-rpaths $TMP/$PKGNAM-$VERSION-$ARCH-$BUILD.txz
+/sbin/makepkg -l y -c n $TMP/$PKGNAM-$VERSION-$ARCH-$BUILD.txz
